#!/usr/bin/bash
i=$1
img_date=$(date -r $i '+%Y%m%d%H%M.%S');
	echo $img_date;
	temp=/tmp/$(basename $i);
	exiftran -2 -o $temp $i; 
	touch -t $img_date $temp;
	mv $temp $i;


#img_date=$(date -r $i '+%Y-%m-%d %H:%M:%S');
#	echo $img_date;
#	temp=/tmp/$(basename $i);
#	exiftran -2 -o $temp $i; 
#	touch -d ${img_date} $temp;
#	mv $temp $i;
